import { pageMetadata } from "@/lib/metadata";
import { projectStories } from "@/lib/project-stories";
import ProjectCard from "@/components/ProjectCard";
import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { projects } from "@/lib/content";
import PageIntro from "@/components/PageIntro";
import NextStep from "@/components/NextStep";
export function generateStaticParams(){return projects.map(p=>({slug:p.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=projects.find(p=>p.slug===slug);if(!p)notFound();return pageMetadata(p.title,p.intro,`/projets/${p.slug}`,p.image)}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=projects.find(p=>p.slug===slug);if(!p)notFound();const story=projectStories[p.slug];return <main id="contenu"><PageIntro label={p.title} parent={{href:"/projets",label:"Projets"}} title={p.title} description={p.intro}/><div className={`project-cover project-${p.slug}`}><Image src={p.image} alt={p.alt} fill sizes="100vw" preload/></div><section className="section project-story"><aside><dl><dt>Pôle</dt><dd><Link href={`/poles/${p.division.toLowerCase()}`}>LMG {p.division} ↗</Link></dd><dt>Univers</dt><dd>{p.context}</dd><dt>Focus</dt><dd>{p.focus}</dd></dl></aside><div><p className="eyebrow">LE PROJET</p><h2>{p.heading}</h2><p className="body-copy">{p.body}</p><a href={p.href} target="_blank" rel="noopener noreferrer" className="text-link">{p.linkLabel} <span aria-hidden="true">↗</span><span className="sr-only"> (nouvel onglet)</span></a></div></section><section className="section project-detail"><div className="project-detail-heading"><p className="eyebrow">{story.label}</p><h2>{story.title}</h2><p className="body-copy">{story.description}</p></div><div className="expertise-grid">{story.chapters.map(([label,title,body],i)=><article key={label}><span className="index">0{i+1} / {label}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section><section className="section section-ice related-project"><div><p className="eyebrow">CONTINUER LA DÉCOUVERTE</p><h2>Un autre regard<br/>sur le groupe.</h2><Link href="/projets" className="text-link">Tous les projets <span aria-hidden="true">↗</span></Link></div><ProjectCard project={projects.find(other=>other.slug!==p.slug)!}/></section><NextStep title="Votre projet, avec LMG." description="Échangeons sur votre univers, vos ambitions et les prochaines étapes." href={`/contact#${p.division.toLowerCase()}`} label="Parlons de votre projet"/></main>}
