import Image from "next/image";
import Link from "next/link";
import PageIntro from "@/components/PageIntro";
import CopyEmail from "@/components/CopyEmail";
import { contactEmail, divisions } from "@/lib/content";
import { pageMetadata } from "@/lib/metadata";

export const metadata = pageMetadata("Presse & médias", "Présentation de Legacy Music Group, logos du portail à télécharger et contact pour vos demandes presse et médias.", "/presse");
const logos = [
  { name: "Logo bleu", file: "lmg-group-blue.webp", background: "light", description: "Déclinaison du portail sur fond clair." },
  { name: "Logo blanc", file: "lmg-group-white.webp", background: "dark", description: "Déclinaison du portail sur fond bleu nuit." },
];
export default function Page() {
  return <main id="contenu"><PageIntro label="Presse & médias" title={"Les repères.\nLes ressources.\nLe bon contact."} description="Une présentation du groupe et des ressources pour vos articles, portraits et prises de parole autour de Legacy Music Group." />
    <nav className="press-nav" aria-label="Ressources presse"><a href="#presentation">Présentation <span aria-hidden="true">↓</span></a><a href="#logos">Logos <span aria-hidden="true">↓</span></a><a href="#contact-presse">Contact presse <span aria-hidden="true">↓</span></a></nav>
    <section id="presentation" className="section press-overview"><div><p className="eyebrow">01 / À PROPOS DE LMG</p><h2>Un groupe.<br />Trois expertises.</h2><Link href="/groupe" className="text-link">Découvrir le groupe <span aria-hidden="true">↗</span></Link></div><div><p className="press-description">Legacy Music Group (LMG) réunit musique, divertissement et création. Le groupe accompagne les talents, les marques et leurs projets à travers trois pôles complémentaires : LMG Music, consacré au développement artistique ; LMG Entertainment, au booking et aux expériences live ; et LMG Agency, à la stratégie, à la création et au digital.</p><a href="/presse/presentation-lmg-group.txt" download="LMG-Group-Presentation.txt" className="text-link">Télécharger la présentation <span className="press-format">TXT</span><span aria-hidden="true">↓</span></a><dl className="press-facts">{divisions.map(division => <div key={division.slug}><dt>LMG {division.name}</dt><dd>{division.field}</dd></div>)}</dl></div></section>
    <section id="logos" className="section section-ice"><div className="section-heading"><p className="eyebrow">02 / IDENTITÉ VISUELLE</p><h2>Les logos du portail.</h2></div><p className="press-intro">Les déclinaisons utilisées sur ce site sont disponibles ci-dessous au format web. Pour une impression, un grand format ou un fichier transparent, contactez le groupe.</p><div className="press-logos">{logos.map(logo => <article key={logo.file}><div className={`press-logo-preview press-logo-${logo.background}`}><Image src={`/images/${logo.file}`} alt={`${logo.name} LMG Group`} width={160} height={160} /></div><div className="press-logo-details"><h3>{logo.name}</h3><p>{logo.description}</p><p className="press-file-info">WebP · 256 × 256 px · fond inclus</p><a href={`/images/${logo.file}`} download={logo.file} className="text-link">Télécharger le logo {logo.background === "light" ? "bleu" : "blanc"}<span aria-hidden="true">↓</span></a></div></article>)}</div></section>
    <section id="contact-presse" className="section press-contact"><div><p className="eyebrow">03 / DEMANDES PRESSE</p><h2>Préparons<br />votre sujet.</h2><p className="body-copy">Interview, présentation du groupe, visuel complémentaire ou information sur un projet : indiquez votre média, votre sujet et votre date de publication envisagée.</p></div><div className="press-contact-details"><a className="button button-white" href={`mailto:${contactEmail}?subject=${encodeURIComponent("LMG Group — Demande presse")}`}>Écrire pour une demande presse <span aria-hidden="true">↗</span></a><a className="press-email" href={`mailto:${contactEmail}`}>{contactEmail}</a><CopyEmail /><p>Pour les photos, crédits et formats spécifiques, précisez l’utilisation prévue dans votre message.</p></div></section>
    <section className="section sibling-section"><p className="eyebrow">POUR POURSUIVRE</p><h2>La vie du groupe.</h2><div className="sibling-links"><Link href="/actualites"><span>Le journal LMG</span><strong>Nos actualités</strong><b aria-hidden="true">↗</b></Link><Link href="/projets"><span>Musique & création</span><strong>Nos projets</strong><b aria-hidden="true">↗</b></Link></div></section>
  </main>;
}
