import { pageMetadata } from "@/lib/metadata";
import Image from "next/image";
import Link from "next/link";
import { projects } from "@/lib/content";
import ProjectCard from "@/components/ProjectCard";
import NewsCard from "@/components/NewsCard";
import { news } from "@/lib/news";
import NextStep from "@/components/NextStep";
export default function HomePage() {
 return <main id="contenu"><section className="home-hero"><div className="hero-orbit" aria-hidden="true"/><div className="hero-copy"><p className="eyebrow">LEGACY MUSIC GROUP</p><h1>La culture.<br/>Les talents.<br/><span>Et la suite.</span></h1><p>Musique, live et création. Un groupe indépendant qui relie les expertises pour faire grandir les projets.</p><Link href="/groupe" className="button button-white">Découvrir le groupe<span aria-hidden="true">↗</span></Link></div><Link href="/projets/fly" className="hero-story"><div className="hero-story-image"><Image src="/images/laam-fly.png" alt="Visuel FLY de LAAM" fill sizes="(max-width: 800px) 85vw, 38vw" preload/></div><div><span>MUSIC / À DÉCOUVRIR</span><strong>LAAM — FLY <span aria-hidden="true">↗</span></strong></div></Link><div className="hero-bottom"><span>UN GROUPE. TROIS UNIVERS.</span><a href="#vision">Explorer <span aria-hidden="true">↓</span></a></div></section><div className="news-strip"><span>À LA UNE</span><Link href="/actualites/un-nouveau-regard-sur-lmg"><b>Groupe</b> Le nouveau portail LMG <span aria-hidden="true">↗</span></Link><Link href="/projets/deepa"><b>Agency</b> Deepa Be Yourself <span aria-hidden="true">↗</span></Link></div><section className="section vision-section" id="vision"><p className="eyebrow">01 / LE GROUPE</p><div><h2>Des métiers singuliers.<br/><span className="blue">Une ambition commune.</span></h2><div className="vision-description"><p>Un artiste développe son univers. Un événement rencontre son public. Une marque trouve sa voix. LMG réunit les expertises qui accompagnent ces trajectoires.</p><Link href="/groupe" className="text-link">Notre vision <span aria-hidden="true">↗</span></Link></div></div></section><section className="section"><div className="section-heading"><p className="eyebrow">02 / LES PROJETS</p><h2>Des idées.<br/>Des expressions concrètes.</h2><Link href="/projets" className="text-link">Explorer les projets <span aria-hidden="true">↗</span></Link></div><div className="project-grid">{projects.map(p=><ProjectCard key={p.slug} project={p}/>)}</div></section><section className="section section-ice"><div className="section-heading"><p className="eyebrow">03 / ACTUALITÉS</p><h2>La vie du groupe.</h2><Link href="/actualites" className="text-link">Toutes les actualités <span aria-hidden="true">↗</span></Link></div><NewsCard article={news[0]}/></section><NextStep/></main>;
}

export const metadata = pageMetadata("Home - LMG Group Portal","Découvrez Legacy Music Group : musique, live et création. Un groupe indépendant, trois expertises complémentaires.","/");
