export const divisions = [
  { slug: "music", name: "Music", number: "01", field: "Musique & développement artistique", headline: "Faire grandir les voix.\nConstruire les trajectoires.", description: "De la première intention à la rencontre avec le public, LMG Music accompagne les artistes et donne une direction à leurs projets.", skills: [["Direction artistique", "Définir un univers, un positionnement et une ligne cohérente autour de chaque artiste."], ["Projets & sorties", "Articuler la musique, l’image et les temps forts d’une sortie pour raconter une même histoire."], ["Développement", "Construire les prochaines étapes, ouvrir les collaborations et inscrire le projet dans la durée."]], contact: "Présenter un projet musical", subject: "LMG Music — Projet artistique", website: "https://legacymusicgroup.fr", project: "fly" },
  { slug: "entertainment", name: "Entertainment", number: "02", field: "Booking & expériences live", headline: "Le talent rencontre\nson public.", description: "LMG Entertainment relie les artistes, les organisateurs et les lieux. Une programmation pensée pour l’identité de chaque événement et l’expérience de son public.", skills: [["Booking", "Identifier les talents et les formats artistiques qui correspondent à votre événement."], ["Programmation", "Donner une direction à l’affiche et construire un ensemble cohérent de performances."], ["Coordination artistique", "Préparer les échanges entre talents et organisateurs, du premier brief au rendez-vous avec le public."]], contact: "Parler de votre événement", subject: "LMG Entertainment — Événement et booking", website: "https://www.instagram.com/entertainment.lmg/", project: null },
  { slug: "agency", name: "Agency", number: "03", field: "Stratégie, création & digital", headline: "Donner une forme\naux ambitions.", description: "LMG Agency accompagne les marques, les entreprises et les talents dans leur communication. Du positionnement à l’expérience digitale, chaque expression répond à une même direction.", skills: [["Stratégie", "Clarifier le positionnement, les messages et les priorités de communication."], ["Identité & contenus", "Concevoir une identité et des contenus qui rendent le projet reconnaissable, sur chaque support."], ["Expériences digitales", "Créer des sites et des parcours pensés pour les personnes qui les utilisent."]], contact: "Parler de votre marque", subject: "LMG Agency — Marque et digital", website: "https://agency.legacymusicgroup.fr", project: "deepa" },
] as const;

export const projects = [
  { slug: "fly", title: "LAAM — FLY", division: "Music", category: "Projet artistique", image: "/images/laam-fly.png", alt: "Visuel du projet FLY de LAAM", intro: "Un projet musical à découvrir dans l’univers de LMG Music.", heading: "Une voix. Un univers.", body: "FLY met à l’honneur LAAM au sein du pôle musical du groupe. Cette sélection donne un premier regard sur le projet et son identité visuelle.", context: "Musique", focus: "Projet & univers artistique", href: "https://legacymusicgroup.fr", linkLabel: "Explorer LMG Music" },
  { slug: "deepa", title: "Deepa Be Yourself", division: "Agency", category: "Expérience digitale", image: "/images/deepa.jpg", alt: "Univers de la maison de parfums Deepa Be Yourself", intro: "L’univers d’une maison de parfums, prolongé dans une expérience digitale.", heading: "Une maison. Une expérience.", body: "Pour Deepa Be Yourself, le projet digital relie la collection, les pages produit et le parcours client. L’enjeu : faire découvrir les parfums dans un univers cohérent et faciliter le passage de la découverte à l’achat.", context: "Parfumerie", focus: "Site & parcours client", href: "https://www.deepabeyourself.com", linkLabel: "Visiter Deepa Be Yourself" },
] as const;
export const contactEmail = "contact@legacymusicgroup.fr";
